name: Push

on: push

jobs:
  spellcheck:
    name: Spell check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check spelling
        uses: crate-ci/typos@master
  test:
    name: Lint, build, and test on node 18.x and ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1
      - name: Lint codebase
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Build codebase
        run: yarn build
